### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by tzvi** [Daplie/letsencrypt-express#52] opened 2016-05-26 14:53 UTC
cert is looking good
[Sanity Check Fail]: a weird object was passed back through le.fetch to lex.fetch
(either missing or malformed certInfo.key and / or certInfo.fullchain)
Unhandled rejection TypeError: undefined is not a function
    at cacheResult (/pano/node_modules/letsencrypt-express/lib/sni-callback.js:116:7)
    at /pano/node_modules/letsencrypt-express/lib/sni-callback.js:189:9
    at /pano/node_modules/letsencrypt/index.js:224:9
    at tryCatcher (/pano/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/pano/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/pano/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/pano/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/pano/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/pano/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/pano/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/pano/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/pano/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/pano/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/pano/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/pano/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/pano/node_modules/bluebird/js/release/promise_array.js:125:19)

**Comment by calrk** [comment] 2016-05-29 02:43
I'm getting the same error.
I used the following command to generate the certificates:
~~~~
sudo letsencrypt certonly --standalone --config-dir /var/lib/letsencrypt --agree-tos --domains server.clarklavery.com --email <email>
~~~~
And my server is running the following code:
~~~~
var LEX = require('letsencrypt-express');

var lex = LEX.create({
  configDir: '/var/lib/letsencrypt/',
  approveRegistration: function (hostname, cb) {
    cb(null, {
      domains: [hostname]
    , email: '<email>'
    , agreeTos: true
    });
  }
});

var express = require('express');
var http = require('http');
var https = require('spdy');

var app = express();

http.createServer(LEX.createAcmeResponder(lex, function redirectHttps(req, res) {
	res.setHeader('Location', 'https://' + req.headers.host + req.url);
	res.statusCode = 302;
	res.end('<!-- Hello Developer Person! Please use HTTPS instead -->');
})).listen(80);

app.use('/', function (req, res) {
	console.log('Endpoint hit!');
	res.end('Hello!');
});

https.createServer(lex.httpsOptions, LEX.createAcmeResponder(lex, app)).listen(443);
~~~~

I get the right response when I curl the http address, but the error log when I curl the https one.

Let me know if there's any config you would like tested or any logs that might help debug this issue if you like.

**Comment by rpp0** [comment] 2016-07-05 15:50
`Unhandled rejection TypeError: undefined is not a function`
What is your node version? E.g. node -v? It seems to me that it is too old.

**Comment by coolaj86** [comment] 2016-08-01 05:38
This is a duplicate of https://github.com/Daplie/node-letsencrypt/issues/23. I'm closing it here because I'm working on it there.

**Closed by coolaj86** 2016-08-01 05:38 UTC
